//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App_234_25.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public int Id { get; set; }
        public string DayOfWeek { get; set; }
        public int LessonNumber { get; set; }
        public Nullable<int> GroupId { get; set; }
        public Nullable<int> LecturerId { get; set; }
        public Nullable<int> RoomId { get; set; }
        public string SubjectName { get; set; }
        public System.DateTime LessonDate { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual Lecturer Lecturer { get; set; }
        public virtual Room Room { get; set; }
    }
}
